### ISSUE TITLE
Some bug

### ISSUE THREAD

**Issue by chentianyu1997** [guskarls/dfl-pens#3]
Dear code author:
Soo surprised to see such a clear project. But when I run it, I met some problems.
Traceback (most recent call last):
  File "C:/dfl-pens-main/dfl-pens-main/main.py", line 224, in <module>
    args.gpu, devicea = set_gpu_and_device(args.gpu)
  File "C:\dfl-pens-main\dfl-pens-main\train_utils.py", line 657, in set_gpu_and_device
    return gpu, device
UnboundLocalError: local variable 'device' referenced before assignment
I have added global in train_util and in main, But still can't work.
Can you check it?
Thank you so much!

**Comment by Gaiety-yu** [comment]
请问你现在找到解决方法了吗？想请教一下!

**Comment by noaonoszko** [comment]
Hi! Sorry for the late reply. I have fixed the bug now, hope it helps. Please let me know if there's something else you need.

**Comment by chentianyu1997** [comment]
没找到 修改过还是有别的问题，你有结果吗？发自我的iPhone------------------ Original ------------------From: Gaiety-yu  ***@***.***>Date: Fri,May 6,2022 3:38 PMTo: guskarls/dfl-pens ***@***.***>Cc: chentianyu1997 ***@***.***>, Author ***@***.***>Subject: Re: [guskarls/dfl-pens] Some bug (Issue #3)
请问你现在找到解决方法了吗？想请教一下!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/guskarls/dfl-pens/issues/3#issuecomment-1119342046",
"url": "https://github.com/guskarls/dfl-pens/issues/3#issuecomment-1119342046",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
